graph TD
  user --> Identity
  Identity --> UserSessionManager
  UserSessionManager --> UserSession-UserId1
  UserSessionManager --> UserSession-UserId2
  UserSessionManager --> UserAuthenticator-Id1
  UserAuthenticator-Id1 --> UserLoader-Id1
  UserSession-UserId1 --> UserLogin-Id1
  UserSession-UserId1 --> UserLogin-Id2

  user --> TerminalManager
  TerminalManager --> Terminal-Id1
  TerminalManager --> Terminal-Id2

  user --> GameHub
