// <auto-generated />
namespace Actor.GameHub.Identity.EntityFrameworkCore.FSharp.Migrations

open System
open Actor.GameHub.Identity.EntityFrameworkCore
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<IdentityDbContext.IdentityDbContext>)>]
[<Migration("20210424070029_IdentityInit")>]
type IdentityInit() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.EnsureSchema(
            name = "Identity"
            ) |> ignore

        migrationBuilder.CreateTable(
            name = "User"
            ,schema = "Identity"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<Guid>(
                        nullable = false
                        ,``type`` = "uniqueidentifier"
                    )
                Username =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(100)"
                        , maxLength = Nullable(100))
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_User", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore

        migrationBuilder.InsertData(
            schema = "Identity",
            table = "User",
            columns = [| "Id"; "Username" |],
            values = array2D [ [ Guid("ac0bdea1-5135-4a88-9e73-0baae707c4d9") :> obj; "lars" :> obj ]; [ Guid("38f4449c-8a87-42f9-aaaf-912212eb33c9") :> obj; "merten" :> obj ]; [ Guid("3e1b64c9-c909-44b8-9649-6ef836a49c52") :> obj; "sam" :> obj ]; [ Guid("ca58076f-cf6d-45d4-9469-3537bcc50b2d") :> obj; "uli" :> obj ] ]
        ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_User_Username"
            ,schema = "Identity"
            ,table = "User"
            ,column = "Username"
            ,unique = true
            ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "User"
            ,schema = "Identity"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityColumns().HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.5")
            |> ignore

        modelBuilder.Entity("Actor.GameHub.Identity.EntityFrameworkCore.UserEntity+UserEntity", (fun b ->

            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier") |> ignore
            b.Property<string>("Username")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("Username")
                .IsUnique() |> ignore

            b.ToTable("User","Identity") |> ignore

            b.HasData([| 
                {| Id = Guid("ac0bdea1-5135-4a88-9e73-0baae707c4d9"); Username = "lars"; |}
                {| Id = Guid("38f4449c-8a87-42f9-aaaf-912212eb33c9"); Username = "merten"; |}
                {| Id = Guid("3e1b64c9-c909-44b8-9649-6ef836a49c52"); Username = "sam"; |}
                {| Id = Guid("ca58076f-cf6d-45d4-9469-3537bcc50b2d"); Username = "uli"; |}
             |]) |> ignore

        )) |> ignore

