// <auto-generated />
namespace Actor.GameHub.Identity.EntityFrameworkCore.FSharp.Migrations

open System
open Actor.GameHub.Identity.EntityFrameworkCore
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<IdentityDbContext.IdentityDbContext>)>]
[<Migration("20210418145003_IdentityInit")>]
type IdentityInit() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.EnsureSchema(
            name = "Identity"
            ) |> ignore

        migrationBuilder.CreateTable(
            name = "User"
            ,schema = "Identity"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<Guid>(
                        nullable = false
                        ,``type`` = "uniqueidentifier"
                    )
                Username =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(100)"
                        , maxLength = Nullable(100))
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_User", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore

        migrationBuilder.InsertData(
            schema = "Identity",
            table = "User",
            columns = [| "Id"; "Username" |],
            values = array2D [ [ Guid("cd735892-e9a7-4b36-b910-03e97a95b421") :> obj; "lars" :> obj ]; [ Guid("94342156-c2ab-433e-8e8a-d000c49a1ae9") :> obj; "merten" :> obj ]; [ Guid("1fe0f5f7-13e6-4a58-87ea-d153951a7c6c") :> obj; "sam" :> obj ]; [ Guid("ff7b5153-2218-45bc-9838-892b99f97b59") :> obj; "uli" :> obj ] ]
        ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_User_Username"
            ,schema = "Identity"
            ,table = "User"
            ,column = "Username"
            ,unique = true
            ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "User"
            ,schema = "Identity"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .HasDefaultSchema("Identity")
            .UseIdentityColumns().HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.5")
            |> ignore

        modelBuilder.Entity("Actor.GameHub.Identity.EntityFrameworkCore.Entities+UserEntity", (fun b ->

            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier") |> ignore
            b.Property<string>("Username")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("Username")
                .IsUnique() |> ignore

            b.ToTable("User") |> ignore

            b.HasData([| 
                {| Id = Guid("cd735892-e9a7-4b36-b910-03e97a95b421"); Username = "lars"; |}
                {| Id = Guid("94342156-c2ab-433e-8e8a-d000c49a1ae9"); Username = "merten"; |}
                {| Id = Guid("1fe0f5f7-13e6-4a58-87ea-d153951a7c6c"); Username = "sam"; |}
                {| Id = Guid("ff7b5153-2218-45bc-9838-892b99f97b59"); Username = "uli"; |}
             |]) |> ignore

        )) |> ignore

