// <auto-generated />
namespace Actor.GameHub.Identity.EntityFrameworkCore.FSharp.Migrations

open System
open Actor.GameHub.Identity.EntityFrameworkCore
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<IdentityDbContext.IdentityDbContext>)>]
[<Migration("20210418164153_IdentityInit")>]
type IdentityInit() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.EnsureSchema(
            name = "Identity"
            ) |> ignore

        migrationBuilder.CreateTable(
            name = "User"
            ,schema = "Identity"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<Guid>(
                        nullable = false
                        ,``type`` = "uniqueidentifier"
                    )
                Username =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(100)"
                        , maxLength = Nullable(100))
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_User", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore

        migrationBuilder.InsertData(
            schema = "Identity",
            table = "User",
            columns = [| "Id"; "Username" |],
            values = array2D [ [ Guid("d727abca-c58a-42d8-9176-e21c4ac906c7") :> obj; "lars" :> obj ]; [ Guid("5451dc48-749d-4d65-b7d3-06bc4853e74e") :> obj; "merten" :> obj ]; [ Guid("8b00bc0c-da63-4be4-9265-cce94044f420") :> obj; "sam" :> obj ]; [ Guid("1a58b2e7-43ca-4c4c-a188-40ff58e33312") :> obj; "uli" :> obj ] ]
        ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_User_Username"
            ,schema = "Identity"
            ,table = "User"
            ,column = "Username"
            ,unique = true
            ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "User"
            ,schema = "Identity"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .HasDefaultSchema("Identity")
            .UseIdentityColumns().HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.5")
            |> ignore

        modelBuilder.Entity("Actor.GameHub.Identity.EntityFrameworkCore.Entities+UserEntity", (fun b ->

            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier") |> ignore
            b.Property<string>("Username")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("Username")
                .IsUnique() |> ignore

            b.ToTable("User") |> ignore

            b.HasData([| 
                {| Id = Guid("d727abca-c58a-42d8-9176-e21c4ac906c7"); Username = "lars"; |}
                {| Id = Guid("5451dc48-749d-4d65-b7d3-06bc4853e74e"); Username = "merten"; |}
                {| Id = Guid("8b00bc0c-da63-4be4-9265-cce94044f420"); Username = "sam"; |}
                {| Id = Guid("1a58b2e7-43ca-4c4c-a188-40ff58e33312"); Username = "uli"; |}
             |]) |> ignore

        )) |> ignore

