// <auto-generated />
namespace Actor.GameHub.Identity.EntityFrameworkCore.FSharp.Migrations

open System
open Actor.GameHub.Identity.EntityFrameworkCore
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<IdentityDbContext.IdentityDbContext>)>]
type IdentityDbContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .HasDefaultSchema("Identity")
            .UseIdentityColumns().HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.5")
            |> ignore

        modelBuilder.Entity("Actor.GameHub.Identity.EntityFrameworkCore.Entities+UserEntity", (fun b ->

            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier") |> ignore
            b.Property<string>("Username")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("Username")
                .IsUnique() |> ignore

            b.ToTable("User") |> ignore

            b.HasData([| 
                {| Id = Guid("cd735892-e9a7-4b36-b910-03e97a95b421"); Username = "lars"; |}
                {| Id = Guid("94342156-c2ab-433e-8e8a-d000c49a1ae9"); Username = "merten"; |}
                {| Id = Guid("1fe0f5f7-13e6-4a58-87ea-d153951a7c6c"); Username = "sam"; |}
                {| Id = Guid("ff7b5153-2218-45bc-9838-892b99f97b59"); Username = "uli"; |}
             |]) |> ignore

        )) |> ignore

