// <auto-generated />
namespace Actor.GameHub.Identity.EntityFrameworkCore.FSharp.Migrations

open System
open Actor.GameHub.Identity.EntityFrameworkCore
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<IdentityDbContext.IdentityDbContext>)>]
type IdentityDbContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .HasDefaultSchema("Identity")
            .UseIdentityColumns().HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.5")
            |> ignore

        modelBuilder.Entity("Actor.GameHub.Identity.EntityFrameworkCore.Entities+UserEntity", (fun b ->

            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier") |> ignore
            b.Property<string>("Username")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("Username")
                .IsUnique() |> ignore

            b.ToTable("User") |> ignore

            b.HasData([| 
                {| Id = Guid("d727abca-c58a-42d8-9176-e21c4ac906c7"); Username = "lars"; |}
                {| Id = Guid("5451dc48-749d-4d65-b7d3-06bc4853e74e"); Username = "merten"; |}
                {| Id = Guid("8b00bc0c-da63-4be4-9265-cce94044f420"); Username = "sam"; |}
                {| Id = Guid("1a58b2e7-43ca-4c4c-a188-40ff58e33312"); Username = "uli"; |}
             |]) |> ignore

        )) |> ignore

