// <auto-generated />
namespace Actor.GameHub.Identity.EntityFrameworkCore.FSharp.Migrations

open System
open Actor.GameHub.Identity.EntityFrameworkCore
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<IdentityDbContext.IdentityDbContext>)>]
type IdentityDbContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityColumns().HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.5")
            |> ignore

        modelBuilder.Entity("Actor.GameHub.Identity.EntityFrameworkCore.UserEntity+UserEntity", (fun b ->

            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier") |> ignore
            b.Property<string>("Username")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("Username")
                .IsUnique() |> ignore

            b.ToTable("User","Identity") |> ignore

            b.HasData([| 
                {| Id = Guid("ac0bdea1-5135-4a88-9e73-0baae707c4d9"); Username = "lars"; |}
                {| Id = Guid("38f4449c-8a87-42f9-aaaf-912212eb33c9"); Username = "merten"; |}
                {| Id = Guid("3e1b64c9-c909-44b8-9649-6ef836a49c52"); Username = "sam"; |}
                {| Id = Guid("ca58076f-cf6d-45d4-9469-3537bcc50b2d"); Username = "uli"; |}
             |]) |> ignore

        )) |> ignore

