// <auto-generated />
using System;
using Actor.GameHub.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Actor.GameHub.Identity.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Actor.GameHub.Identity.EntityFrameworkCore.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3212fed2-6246-46a4-8959-79748024418e"),
                            Username = "lars"
                        },
                        new
                        {
                            Id = new Guid("57e16b30-16fb-4203-8f22-7417e3ad91de"),
                            Username = "merten"
                        },
                        new
                        {
                            Id = new Guid("aa493230-83b1-4cf6-b1d8-69aaf98e767d"),
                            Username = "sam"
                        },
                        new
                        {
                            Id = new Guid("a1bc719c-2726-482e-bec9-7f826838d35f"),
                            Username = "uli"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
